### ISSUE TITLE
PHP-CS-Fixer v3 support?

### ISSUE THREAD

**Issue by ankurk91** [permafrost-dev/phpcsfixer-preset#4]
Hi

PHP-CS-Fixer v3 has been released

Here is the upgrade guide
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/UPGRADE-v3.md

**Comment by patinthehat** [comment]
Thanks for the heads up! I'll add support as soon as possible.

**Comment by patinthehat** [comment]
@ankurk91 I've released v2.0.0 of the package, which supports `php-cs-fixer` v3.  Thanks again!

**Comment by ankurk91** [comment]
Please update the read me instruction to have file name as `.php-cs-fixer.php`
