### ISSUE TITLE
Symfony Console 6 | Laravel 9 support.

### ISSUE THREAD

**Issue by patrickcurl** [permafrost-dev/phpcsfixer-preset#5]
Breaks on laravel 9 / Symfony Console 6 is requirement.

**Comment by patinthehat** [comment]
@patrickcurl I'd welcome a PR to resolve the issue!

**Comment by ankurk91** [comment]
@patinthehat 
Please tag a new version

**Comment by patinthehat** [comment]
@ankurk91 Thanks for the reminder - done.
